PRODUCT_VERSION_MAJOR = 8.1
PRODUCT_VERSION_MINOR = Beta
PRODUCT_VERSION_MAINTENANCE = 1.0
ELIXIR_POSTFIX := -$(shell date +"%Y%m%d-%H%M")
ifdef ELIXIR_BUILD_EXTRA
    ELIXIR_POSTFIX := -$(ELIXIR_BUILD_EXTRA)
endif

ifndef ELIXIR_BUILD_TYPE
    ELIXIR_BUILD_TYPE := UNOFFICIAL
endif

# Set all versions
ELIXIR_VERSION := Elixir-$(ELIXIR_BUILD)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(ELIXIR_BUILD_TYPE)$(ELIXIR_POSTFIX)
ELIXIR_MOD_VERSION := Elixir-$(ELIXIR_BUILD)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(ELIXIR_BUILD_TYPE)$(ELIXIR_POSTFIX)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    elixir.ota.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE) \
    ro.elixir.version=$(ELIXIR_VERSION) \
    ro.modversion=$(ELIXIR_MOD_VERSION) \
    ro.elixir.buildtype=$(ELIXIR_BUILD_TYPE)
